### ISSUE TITLE
Error loading savegame after latest update 0.11.60

### ISSUE THREAD

**Issue by SBliveNL** [Scordium/FicsitWiremod#2]
After the latest update 0.11.60 I can no longer load my save game, I immediately get an unreal error. This error is listed below. version 0.11.53 does work.

Version: 211839, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Assertion failed: IsValidIndex(Index) [File:D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Public\UObject/UObjectArray.h] [Line: 508] IsValidIndex(1143739648)

FactoryGame_Core_Win64_Shipping!AssertFailedImplV() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
FactoryGame_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
FactoryGame_CoreUObject_Win64_Shipping!DispatchCheckVerify<void,<lambda_45210ce67bf19dafedfd688f8c0733a9> >() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Misc\AssertionMacros.h:165]
FactoryGame_CoreUObject_Win64_Shipping!TFastReferenceCollector<FGCReferenceProcessor<9>,FGCCollector<9>,FGCArrayPool,9>::ProcessObjectArray() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Public\UObject\FastReferenceCollector.h:751]
FactoryGame_CoreUObject_Win64_Shipping!TFastReferenceCollector<FGCReferenceProcessor<9>,FGCCollector<9>,FGCArrayPool,9>::FCollectorTaskQueue::DoTask() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Public\UObject\FastReferenceCollector.h:403]
FactoryGame_CoreUObject_Win64_Shipping!TGraphTask<TFastReferenceCollector<FGCReferenceProcessor<9>,FGCCollector<9>,FGCArrayPool,9>::FCollectorTaskProcessorTask>::ExecuteTask() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:891]
FactoryGame_Core_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:887]
FactoryGame_Core_Win64_Shipping!FTaskThreadBase::Run() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:541]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

**Comment by Scordium** [comment]
Working on this problem already, some weird bug with garbage collection

**Comment by Scordium** [comment]
Fixed. Await the patch on SMR in 20-30 minutes.
