### ISSUE TITLE
scrolling belt also changes hotbar

### ISSUE THREAD

**Issue by ninjacm** [Scordium/FicsitWiremod#4]
When you have the wire tool equipped and scroll through your tools it changes the current hotbar each time you pass over the wire tool. It as if you are holding Left Alt. 

Doesn't seem to be a problem with the debug tool. 

reproduced multiple times in a single session, and also after restarting the game, and SMM launcher.

**Comment by Scordium** [comment]
Already reported in discord. Do not create bug reports here.
